### ISSUE TITLE
two OTA partition how to?

### ISSUE THREAD

**Issue by kenjican** [mkomon/uota#3]
I compiled a ESP32 firmware , and now , boot partition is ota_0. uota could download and unzip firmware I put in a LAN web server. It's good. 

My problem is how to copy this firmware downloaded in ota_0 and copy it to ota_1? 

Since copied to ota_1. I could set boot partition by esp32.Partition.set_boot()

**Comment by ThinkTransit** [comment]
Have you tried mounting ota_1 with os.mount()?

**Comment by mkomon** [comment]
Apologies for not responding sooner. To clarify, this library cannot update MicroPython firmware to a new version - it can only update (application) code written in MicroPython. I may really need to update the documentation and use the word "application" instead of "firmware".

**Comment by mkomon** [comment]
Closing as old and non-actionable.
